/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Risk3;
import java.awt.event.ActionListener;
/**
 *
 * @author Rafael Angel MF
 */
public class FrmMenuTerritorio extends javax.swing.JFrame {
    
    public void enableTrasladarse(boolean activado){
        this.jBtnTrasladarse_a_un_territorio_propio.setEnabled(activado);
    }
    
    public void enableColinizar(boolean activado){
        this.jBtnColonizar.setEnabled(activado);
    }
    
    /**
     * Activa o desactiva los botones para crear unidades.
     * @param activado Un booleano, true para activar los botones, false para desactivarlos.
     */
    public void enableCrear(boolean activado){
        this.jbtnCrearTanque.setEnabled(activado);
        this.jBtnCrearSoldado.setEnabled(activado);
        this.jBtnCrearCasa.setEnabled(activado);
    }

    public String getEtiquetaCrearTanque(){
        return jbtnCrearTanque.getText();
    }
    
    public String getEtiquetaCrearSoldado(){
        return jBtnCrearSoldado.getText();
    }
    
    public String getEtiquetaCrearCasa(){
        return jBtnCrearCasa.getText();
    }
    
    public String getEtiquetaColonizar(){
        return jBtnColonizar.getText();
    }
    
    public String getEtiquetaTrasladarse(){
        return this.jBtnTrasladarse_a_un_territorio_propio.getText();
    }
    
    public void addControladorActionListener(ActionListener nuevoActionListener){
        this.jbtnCrearTanque.addActionListener(nuevoActionListener);
        this.jBtnCrearSoldado.addActionListener(nuevoActionListener);
        this.jBtnCrearCasa.addActionListener(nuevoActionListener);
        this.jBtnColonizar.addActionListener(nuevoActionListener);
        this.jBtnTrasladarse_a_un_territorio_propio.addActionListener(nuevoActionListener);
    }
    
    /**
     * Creates new form FrmMenuTerritorio
     */
    public FrmMenuTerritorio() {
        initComponents();
        this.setBounds(300, 100, 320, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCrearCasa = new javax.swing.JButton();
        jBtnCrearSoldado = new javax.swing.JButton();
        jbtnCrearTanque = new javax.swing.JButton();
        jBtnColonizar = new javax.swing.JButton();
        jBtnTrasladarse_a_un_territorio_propio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnCrearCasa.setText("Crear casa");
        jBtnCrearCasa.setEnabled(false);
        jBtnCrearCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearCasaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCrearCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 120, -1));

        jBtnCrearSoldado.setText("Crear soldado");
        jBtnCrearSoldado.setEnabled(false);
        jBtnCrearSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearSoldadoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCrearSoldado, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 120, -1));

        jbtnCrearTanque.setText("Crear tanque");
        jbtnCrearTanque.setEnabled(false);
        jbtnCrearTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearTanqueActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCrearTanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 13, 120, -1));

        jBtnColonizar.setText("Colonizar");
        jBtnColonizar.setEnabled(false);
        jBtnColonizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnColonizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnColonizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, -1));

        jBtnTrasladarse_a_un_territorio_propio.setText("Trasladarse");
        jBtnTrasladarse_a_un_territorio_propio.setToolTipText("Se mueve a un territorio propio");
        jBtnTrasladarse_a_un_territorio_propio.setEnabled(false);
        getContentPane().add(jBtnTrasladarse_a_un_territorio_propio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCrearCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearCasaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCrearCasaActionPerformed

    private void jBtnCrearSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearSoldadoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCrearSoldadoActionPerformed

    private void jbtnCrearTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearTanqueActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCrearTanqueActionPerformed

    private void jBtnColonizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnColonizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnColonizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTerritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTerritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTerritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTerritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMenuTerritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnColonizar;
    private javax.swing.JButton jBtnCrearCasa;
    private javax.swing.JButton jBtnCrearSoldado;
    private javax.swing.JButton jBtnTrasladarse_a_un_territorio_propio;
    private javax.swing.JButton jbtnCrearTanque;
    // End of variables declaration//GEN-END:variables
}
