/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Risk3;

import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
/**
 * Agregar un form menu.
 * @author Rafael Angel MF
 */
public class jpTerritorio extends javax.swing.JPanel {
    public void enableBtnAcciones(boolean activado){
        jBtnAcciones.setEnabled(activado);
    }

//Repetido
    public boolean getSeleccionado(){
        return this.jChkSeleccionar.isSelected();
    }

    public void addBtnAccionesControlador(ActionListener nuevo_controlador){
        jBtnAcciones.addActionListener(nuevo_controlador);
    }
    
    /**
     * Numero respecto al id de la matriz de territorios.
     */
    private int numeroDelTerritorio=-1;
    /**
     * Numero respecto al id de la matriz de territorios.
     * @param nuevo_nuemero Un numero positivo.
     */
    public void setNumeroDelTerritorio(int nuevo_nuemero){
        numeroDelTerritorio=nuevo_nuemero;
    }
    /**
     * Numero respecto al id de la matriz de territorios.
     * @return Retorna un numero positivo entre cero y n cantidad.
     */
    public int getNumeroDelTerritorio(){
        return numeroDelTerritorio;
    }

    private TerritorioRisk3 territorio=null;
    public void setTerritorio(TerritorioRisk3 nuevo_territorio){
        territorio=nuevo_territorio;
//        JOptionPane.showMessageDialog(null, territorio.getSoldados()+ " soldados");
        this.jLCasas.setText(territorio.getCasas()+" casas");
        this.jLSoldados.setText(territorio.getSoldados()+ " soldados");
        this.jLTanques.setText(territorio.getTanques()+ " tanques");
        this.jLRecursos.setText(territorio.getRecursosDeLaCivilizacion()+ " recursos");
        this.jChkSeleccionar.setSelected(territorio.getSeleccionado());
        this.jLFaccion.setText("Faccion " + territorio.getFaccion());
    }
    
    public TerritorioRisk3 getTerritorio(){
        territorio.setSeleccionado(this.getSeleccionado());
        return territorio;
    }
    /**
     * Creates new form jpTerritorio
     */
    public jpTerritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCasas = new javax.swing.JLabel();
        jLSoldados = new javax.swing.JLabel();
        jLTanques = new javax.swing.JLabel();
        jLRecursos = new javax.swing.JLabel();
        jChkSeleccionar = new javax.swing.JCheckBox();
        jBtnAcciones = new javax.swing.JButton();
        jLFaccion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCasas.setText("Casas");
        add(jLCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLSoldados.setText("Soldados");
        add(jLSoldados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLTanques.setText("Tanques");
        add(jLTanques, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLRecursos.setText("Recursos");
        add(jLRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jChkSeleccionar.setText("Seleccionar");
        add(jChkSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        jBtnAcciones.setText("Acciones");
        jBtnAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAccionesActionPerformed(evt);
            }
        });
        add(jBtnAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLFaccion.setText("Faccion?");
        add(jLFaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void addChkActionListener(ActionListener nuevoActionListener){
        jChkSeleccionar.addActionListener(nuevoActionListener);
    }
    
    
//    private boolean seleccionado=false;

    /**
     * Para el oponente virtual.
     * @param seleccionarlo Un valor booleano.
     */
    public void setSeleccionado(boolean seleccionarlo){
//        seleccionado=seleccionarlo;
        jChkSeleccionar.setSelected(seleccionarlo);
    }
    
    private void jBtnAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAccionesActionPerformed
//        frmMenu.setVisible(seleccionado);
    }//GEN-LAST:event_jBtnAccionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAcciones;
    private javax.swing.JCheckBox jChkSeleccionar;
    private javax.swing.JLabel jLCasas;
    private javax.swing.JLabel jLFaccion;
    private javax.swing.JLabel jLRecursos;
    private javax.swing.JLabel jLSoldados;
    private javax.swing.JLabel jLTanques;
    // End of variables declaration//GEN-END:variables
}
