/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package juegoConJLabels;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jugador
 */
public class jPCamino extends javax.swing.JPanel {
    class Hilo extends Thread{
        
        public Hilo(){
        }
        
        private boolean parar=false;
        
        @Override
        public void run(){
            while(parar!=true){
                if(feromonas>0.1){
                    feromonas-=tasaDeEvaporasion;
                }
                try {
                    sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(jPJuego.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }
    
    private double tasaDeEvaporasion=0.001;
    private double feromonas=0.1;
    
    public void setFeromonas(double nuevas_feromonas){
        this.feromonas=nuevas_feromonas;
    }
    
    public double getFeromonas(){
        return this.feromonas;
    }
    
    
    /**
     * Creates new form jPCamino
     */
    public jPCamino() {
        initComponents();
        Hilo h=new Hilo();
        h.start();
//        jLbCamino.setBounds(0,0,this.getWidth()-10,this.getHeight()-10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 204, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
