/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LabelAnimado;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Jugador
 */
public class FrmLabelAnimado extends javax.swing.JFrame {

    
    class Hilo extends Thread{
        
        public Hilo(){
        }
        
      public int numeroAleatorio(int Min, int Max){
        return (int)(Math.random()*(Max-Min+1)+Min);
    }
        
        private int vX=0, vXContrario=500;
        private boolean parar=false;
        private JLabel []mJlAnimados=new JLabel[4];
        
        @Override
        public void run(){
            while(parar!=true){
                
                
//                for(int i=0; i<mJlAnimados.length;i++){
                    repaint();
                    try{
                        for(int i=0; i<mJlAnimados.length;i++){
                            mJlAnimados[i].setVisible(false);
                            mJlAnimados[i]=null;
                        }
                        
                    }catch(Exception e){}
                    mJlAnimados[0]=new JLabel();
                    mJlAnimados[1]=new JLabel();
//                    vX=numeroAleatorio(5,500);
//                    mJlAnimados[i].setIcon(getIcono1());
//                    mJlAnimados[i].setVisible(true);
//                    mJlAnimados[i].setBounds(vX, numeroAleatorio(5,500), 50, 50);
//            //        absoluto=new AbsoluteConstraints(x, y, 1, -1);
//                    add(mJlAnimados[i]);
                    colocarLabel(mJlAnimados[0],vX,100, getIcono1());
                    colocarLabel(mJlAnimados[1],vXContrario,100, getIcono2());
//                    System.out.println("x="+mJlAnimados[i].getX()+", y=" +mJlAnimados[i].getY());
                    vX++;
                    vXContrario--;

                    if(mJlAnimados[0].getBounds().intersects(mJlAnimados[1].getBounds())==true){
                        colocarLabel(mJlAnimados[0],mJlAnimados[0].getX(),mJlAnimados[0].getY(),explosion());
                        parar=true;
                        try {
                            sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(FrmLabelAnimado.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try{
                            for(int i=0; i<mJlAnimados.length;i++){
                                mJlAnimados[i].setVisible(false);
                                mJlAnimados[i]=null;
                            }

                        }catch(Exception e){}
                    }
//                }
                try {
                    sleep(20);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FrmLabelAnimado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    private ImageIcon getIcono1(){
        return new ImageIcon(getClass().getResource("/coliciones/agregar.png"));
    }
    
    private ImageIcon getIcono2(){
        return new ImageIcon(getClass().getResource("/coliciones/modificar.png"));
    }
    
    private ImageIcon explosion(){
        return new ImageIcon(getClass().getResource("/coliciones/Explocion.gif"));
    }
    
//    private int v=0;
//    @Override
//    public void paint(Graphics g){
////        colocarLabel(jLbAnimasion,v,jLbAnimado.getY(), getIcono1());
////        v+=50;
//    }
    /**
     * Label del experimento.
     */
    
    private AbsoluteConstraints absoluto;
    /**
     * Coloca un label en el form.
     * @param unLabel Un objeto Jlabel.
     * @param x Una coordenada x del form.
     * @param y Una coordenada y del form.
     */
    private void colocarLabel(JLabel unLabel, int x, int y, ImageIcon icono){
        unLabel.setIcon(icono);
        unLabel.setVisible(true);
        unLabel.setBounds(x, y, 100, 100);
//        absoluto=new AbsoluteConstraints(x, y, 1, -1);
        this.add(unLabel);
    }
    /**
     * Creates new form FrmLabelAnimado
     */
    public FrmLabelAnimado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpLienzoAmbiente1 = new ejemploLabel.jpLienzoAmbiente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("Activar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 69, 25);
        getContentPane().add(jpLienzoAmbiente1);
        jpLienzoAmbiente1.setBounds(170, 30, 670, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Hilo h=new Hilo();
        h.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLabelAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLabelAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLabelAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLabelAnimado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLabelAnimado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private ejemploLabel.jpLienzoAmbiente jpLienzoAmbiente1;
    // End of variables declaration//GEN-END:variables
}
