/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package investigacionSprites;
import java.applet.AudioClip;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImageOp;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Rafae
 */
public class frmAudio extends javax.swing.JFrame {

    /**
     * Creates new form frmAudio
     */
    public frmAudio() {
        initComponents();
//        h.start();
//        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Audio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g){
        Graphics2D g2D;
        g2D=(Graphics2D)g;
        int incrementX=(h.incremento%7)*90;
        int incrementY=(h.incremento/1)*90;
        g2D.drawImage(h.img,h.anchura, h.altura+100,h.anchura,100+h.altura,incrementX,
                incrementY,incrementX*100,incrementY*100,this);
//        repaint();
    }
    
    private HiloSprite h=new HiloSprite();
    
    public class HiloSprite extends Thread{
        public Image img;
        private int incremento=0;
        private Toolkit toolkit=Toolkit.getDefaultToolkit();
        public final int anchura=185;//.71428571428571428571428571429;
        public final int altura=300;
        public void sprite(){
            
            img=toolkit.getImage(getClass().getResource("/Experimentos/Sprite abeja.jpg"));
        }
        
        @Override
        public void run(){
            
            try {
                sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(frmAudio.class.getName()).log(Level.SEVERE, null, ex);
            }
            incremento++;
        }
    }
    
    protected void reproducirAudio(){
//        AudioClip audio;
//        final String  RUTA="/Experimentos/CA-March-On-FULL-Loop.wav";
//        audio=java.applet.Applet.newAudioClip(getClass().getResource(RUTA));//(new URL(""));
//        audio.play();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmAudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
