/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package investigacionSprites;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Rafael
 * Jueves 17 de febrero del 2022.
 * El codigo no funcionó.
 * La investigacion continua.
 * Pero solo era para ver si se podia extraer algo para integrarlo a la investigacion de los Sprites.
 * De por si no detecta las imagenes en la carpeta.
 */
public class PanelBufferedImageEnImage extends javax.swing.JPanel {
    
    private BufferedImage []allimages;
    
    public void Buffered_en_Image(){
        File path=new File("/Experimentos/BB");
        System.out.println("Hola " +path.listFiles());
        File []allFiles=path.listFiles();

        try {        allimages=new BufferedImage[allFiles.length];
        JLabel []mjLFotos=new JLabel[allFiles.length];
        for (int i=0;i<allFiles.length;i++){
            try{
                mjLFotos [i]=new JLabel();
//                Icon icono=new ImageIcon();
//                icono=(Icon) ImageIO.read(allFiles[i]);
                mjLFotos [i].setIcon((Icon) ImageIO.read(allFiles[i]));
                mjLFotos [i].setText(""+i);
                mjLFotos [i].setVisible(true);
                this.add(mjLFotos [i]);
//                allimages= ImageIO.read(allFiles[i]);
            }catch(Exception e){
            }
        }
            this.jLabel1.setIcon((Icon) ImageIO.read(allFiles[0]));
        } catch (IOException ex) {
            Logger.getLogger(PanelBufferedImageEnImage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * Creates new form PanelBufferedImageEnImage
     */
    public PanelBufferedImageEnImage() {
        initComponents();
        Buffered_en_Image();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
