/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemploLabel;

/**
 *
 * @author Jugador
 */
public class FrmEjemplo extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjemplo
     */
    public FrmEjemplo() {
        initComponents();
        this.setBounds(100, 100, 1000, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDerecha1 = new javax.swing.JButton();
        jbtnAbajo = new javax.swing.JButton();
        jbtnArriba1 = new javax.swing.JButton();
        jbtnIzquierda1 = new javax.swing.JButton();
        btnDiagonalSuperior = new javax.swing.JButton();
        btnDigonalInferior = new javax.swing.JButton();
        btnInversaDiagonalinferior = new javax.swing.JButton();
        btnInversaDiagonalSuperior = new javax.swing.JButton();
        jLControlesDeMovimientos = new javax.swing.JLabel();
        jpLienzoAmbiente1 = new ejemploLabel.jpLienzoAmbiente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jbtnDerecha1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDerecha1.setText("dr");
        jbtnDerecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDerecha1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDerecha1);
        jbtnDerecha1.setBounds(740, 110, 90, 40);

        jbtnAbajo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnAbajo.setText("Abajo");
        jbtnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAbajoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAbajo);
        jbtnAbajo.setBounds(740, 170, 90, 40);

        jbtnArriba1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnArriba1.setText("Arriba");
        jbtnArriba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnArriba1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnArriba1);
        jbtnArriba1.setBounds(640, 170, 90, 40);

        jbtnIzquierda1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnIzquierda1.setText("iz");
        jbtnIzquierda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzquierda1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIzquierda1);
        jbtnIzquierda1.setBounds(640, 110, 90, 33);

        btnDiagonalSuperior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDiagonalSuperior.setText("Diagonal superior");
        btnDiagonalSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalSuperiorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagonalSuperior);
        btnDiagonalSuperior.setBounds(670, 230, 130, 30);

        btnDigonalInferior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDigonalInferior.setText("diagonal inferior");
        btnDigonalInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigonalInferiorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigonalInferior);
        btnDigonalInferior.setBounds(670, 270, 130, 30);

        btnInversaDiagonalinferior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInversaDiagonalinferior.setText("inversa diagonal inferior");
        btnInversaDiagonalinferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversaDiagonalinferiorActionPerformed(evt);
            }
        });
        getContentPane().add(btnInversaDiagonalinferior);
        btnInversaDiagonalinferior.setBounds(640, 360, 190, 30);

        btnInversaDiagonalSuperior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInversaDiagonalSuperior.setText("inversa Diagonal superior");
        btnInversaDiagonalSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversaDiagonalSuperiorActionPerformed(evt);
            }
        });
        getContentPane().add(btnInversaDiagonalSuperior);
        btnInversaDiagonalSuperior.setBounds(640, 310, 190, 30);

        jLControlesDeMovimientos.setText("Controles de movimientos");
        getContentPane().add(jLControlesDeMovimientos);
        jLControlesDeMovimientos.setBounds(640, 50, 180, 40);

        jpLienzoAmbiente1.setVelocidad(25);
        getContentPane().add(jpLienzoAmbiente1);
        jpLienzoAmbiente1.setBounds(30, 10, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzquierda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzquierda1ActionPerformed
        jpLienzoAmbiente1.moverIzquierda();
    }//GEN-LAST:event_jbtnIzquierda1ActionPerformed

    private void jbtnDerecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDerecha1ActionPerformed
        jpLienzoAmbiente1.moverDerecha();
    }//GEN-LAST:event_jbtnDerecha1ActionPerformed

    private void jbtnArriba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnArriba1ActionPerformed
        jpLienzoAmbiente1.moverArriba();
    }//GEN-LAST:event_jbtnArriba1ActionPerformed

    private void jbtnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAbajoActionPerformed
        jpLienzoAmbiente1.moverAbajo();
    }//GEN-LAST:event_jbtnAbajoActionPerformed

    private void btnDiagonalSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalSuperiorActionPerformed
        jpLienzoAmbiente1.moverDiagonalSuperior();
    }//GEN-LAST:event_btnDiagonalSuperiorActionPerformed

    private void btnDigonalInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigonalInferiorActionPerformed
        jpLienzoAmbiente1.moverDiagonalInferior();
    }//GEN-LAST:event_btnDigonalInferiorActionPerformed

    private void btnInversaDiagonalSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversaDiagonalSuperiorActionPerformed
        jpLienzoAmbiente1.moverDiagonalSuperiorReversa();
    }//GEN-LAST:event_btnInversaDiagonalSuperiorActionPerformed

    private void btnInversaDiagonalinferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversaDiagonalinferiorActionPerformed
        jpLienzoAmbiente1.moverDiagonalInferiorReversa();
    }//GEN-LAST:event_btnInversaDiagonalinferiorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagonalSuperior;
    private javax.swing.JButton btnDigonalInferior;
    private javax.swing.JButton btnInversaDiagonalSuperior;
    private javax.swing.JButton btnInversaDiagonalinferior;
    private javax.swing.JLabel jLControlesDeMovimientos;
    private javax.swing.JButton jbtnAbajo;
    private javax.swing.JButton jbtnArriba1;
    private javax.swing.JButton jbtnDerecha1;
    private javax.swing.JButton jbtnIzquierda1;
    private ejemploLabel.jpLienzoAmbiente jpLienzoAmbiente1;
    // End of variables declaration//GEN-END:variables
}
