/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Experimentos;

import java.awt.event.KeyEvent;

/**
 *
 * @author Rafae
 */
public class frmSprite2 extends javax.swing.JFrame {

    private int x;
    private int y;
    
    /**
     * Creates new form frmSprite2
     */
    public frmSprite2() {
        initComponents();
        jPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLUnidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coliciones/agregar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLUnidad)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public  int []pixeles;
    private int alto, ancho;
    
    public void limpiar(){
        for (int i=0;i<pixeles.length;i++){
            pixeles[i]=0;
        }
    }
    
    private int posicionY=0;
            
    public void mostrar(int compensacionX,int compensacionY){
        for(int idY=0;idY<alto;idY++){
           posicionY=idY+compensacionY;
           if(posicionY<0||posicionY>alto){
               continue;//No es necesario pero asi lo dice el entrenamiento. Ademas esta hija de puta palabra bloque el codigo que esta debajo de ella.
           }
        }
        
        for(int idX=0;idX<ancho;idX++){
           int posicionX=idX+compensacionX;
           if(posicionX<0||posicionX>ancho){
//               continue;//No es necesario pero asi lo dice el entrenamiento.
               //Coordenadas de 2 ejes en un vector o matris de una sola dimencion (posicionX+posicionY*ancho).
               //Temporal, se pondra avanzado más adelante.
              
               //(idX & frmSprite2.MASCAR_SPRITE)= si idX sobre pasa el valor de MASCAR_SPRITE entonces darle a idX valor cero.
               pixeles[posicionX+posicionY*ancho]=Sprite.ambiente.pixeles[(idX & frmSprite2.MASCAR_SPRITE)+(y & frmSprite2.MASCAR_SPRITE)* frmSprite2.LADO_SPRITE ];
           }    
       } 
    }
    //varaibles temporales
    /**
     * Tamaño del sprite.
     */
    public  static final int LADO_SPRITE=40;
    private  static final int MASCAR_SPRITE=LADO_SPRITE-1;
    //end variables temporales.
    
    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        x=jLUnidad.getX();
        y=jLUnidad.getY();
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN:
                if(jLUnidad.getY()>=10){
                    jLUnidad.setLocation(jLUnidad.getX(), jLUnidad.getY()+5);
                }else{
                    jLUnidad.setLocation(jLUnidad.getX(),10);
                }
                break;
            case KeyEvent.VK_UP:
                if(jLUnidad.getY()<=300){
                    jLUnidad.setLocation(jLUnidad.getX(), jLUnidad.getY()-5);
                }else{
                    jLUnidad.setLocation(jLUnidad.getX(), 300);
                }
                break;
            case KeyEvent.VK_RIGHT:
                if(jLUnidad.getX()<=750){
                    jLUnidad.setLocation(jLUnidad.getX()+5, jLUnidad.getY());
                }else{
                    jLUnidad.setLocation(800, jLUnidad.getY());
                }
                break;
                case KeyEvent.VK_LEFT:
                if(jLUnidad.getX()>=10){
                    jLUnidad.setLocation(jLUnidad.getX()-5, jLUnidad.getY());
                }else{
                    jLUnidad.setLocation(10, jLUnidad.getY());
                }
                break;
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSprite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSprite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSprite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSprite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSprite2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLUnidad;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
