/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Autocorreccion;

/**
 *
 * @author Jugador
 */
public class Autocorreccion extends javax.swing.JPanel {
    
    
    private final class Diccionario{
        public String []mDiccionarioFaltas={"asi", "vb6", "csharp"};
        public String []mDiccionarioCorrectas={"así", "Visual Basic 6.0", "C#"};
        public String getCorrecion(String texto){
            
            
            for (int c=0; c<mDiccionarioFaltas.length; c++){
                System.out.println(texto + "==" + mDiccionarioFaltas[c]);
                if(mDiccionarioFaltas[c].equals(texto)==true){
                    System.out.println("Correccion " + mDiccionarioCorrectas[c]);
                    return mDiccionarioCorrectas[c];
                }
            }
            return texto;
        }
    }
    
    private String actual="";
    private String texto="";
    private Diccionario diccionario=new Diccionario();
    private int conteoDeBorrado=0;
    private boolean operarDespuesDeBorrar=false;

    /**
     * Creates new form Autocorreccion
     */
    public Autocorreccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Autocorreccion");
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 350, 190);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        //       System.out.println("getKeyCode= " + evt.getKeyCode());
        //        System.out.println("getKeyChar= " + evt.getKeyChar());
        texto=jTextArea1.getText();

        if(evt.getKeyCode()==32 || evt.getKeyCode()==46 || evt.getKeyCode()==44 || evt.getKeyCode()==16 ||evt.getKeyCode()==8){
            jTextArea1.setText(texto.replace(actual, diccionario.getCorrecion(actual)));
            if(actual.length()==0 ){

                jTextArea1.setText(texto.replace(jTextArea1.getText(), diccionario.getCorrecion(jTextArea1.getText())));
                System.out.println("cor jTextArea1.getText()="+jTextArea1.getText()+"*");
                System.out.println("Corrigiendo="+diccionario.getCorrecion(actual));
            }else{
                jTextArea1.setText(texto.replace(actual, diccionario.getCorrecion(actual)));
                //                System.out.println("cor actual="+actual+"*");
                //                System.out.println("Corrigiendo="+diccionario.getCorrecion(actual));
            }

            actual="";
        }
        if(evt.getKeyCode()!=32 || evt.getKeyCode()!=8|| evt.getKeyCode()!=46 || evt.getKeyCode()!=44 || evt.getKeyCode()!=16){
            conteoDeBorrado=0;
            actual+=evt.getKeyChar() + "";
            String r="";
            try{
                r=actual.substring(1);
                actual=actual.replace((char)32+"", r);
            }catch(Exception e){
                r=actual;
            }
            System.out.println("actual="+actual+"*");
        }

        //        System.out.println("getKeyLocation= " + evt.getKeyLocation());
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        //        System.out.println("getKeyCode= " + evt.getKeyCode());
        //        System.out.println("getKeyChar= " + evt.getKeyChar());
        //        System.out.println("getKeyLocation= " + evt.getKeyLocation());
    }//GEN-LAST:event_jTextArea1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
