/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Datos;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jugador
 */
public abstract class FrmCuadricula extends javax.swing.JFrame {

    public void setTableModel(DefaultTableModel nuevoDefaultTableModel){
        this.jTable1.setModel(nuevoDefaultTableModel);
    }
    
//    /**
//     * Creates new form FrmCuadricula
//     */
//    public FrmCuadricula() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuArchivo = new javax.swing.JMenu();
        jMnuiGuardarSemana = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuiSeleccionarOtraSemana = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 370));

        jMnuArchivo.setText("Archivo");

        jMnuiGuardarSemana.setText("GuardarSemana");
        jMnuiGuardarSemana.setToolTipText("");
        jMnuiGuardarSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuiGuardarSemanaActionPerformed(evt);
            }
        });
        jMnuArchivo.add(jMnuiGuardarSemana);
        jMnuArchivo.add(jSeparator1);

        jMnuiSeleccionarOtraSemana.setText("Seleccionar otra semana");
        jMnuiSeleccionarOtraSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuiSeleccionarOtraSemanaActionPerformed(evt);
            }
        });
        jMnuArchivo.add(jMnuiSeleccionarOtraSemana);
        jMnuArchivo.add(jSeparator2);

        jMnuiSalir.setText("Salir");
        jMnuiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuiSalirActionPerformed(evt);
            }
        });
        jMnuArchivo.add(jMnuiSalir);

        jMenuBar1.add(jMnuArchivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuiSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMnuiSalirActionPerformed

    /**
     * Se debe crear una comprobacion de que no se valla a guardar 2 veces la misma semana.
     */
    public abstract void eveguardarSemana();
    
    private void jMnuiGuardarSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuiGuardarSemanaActionPerformed
        eveguardarSemana();
    }//GEN-LAST:event_jMnuiGuardarSemanaActionPerformed

    private void jMnuiSeleccionarOtraSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuiSeleccionarOtraSemanaActionPerformed
        FrmBuscar f=new FrmBuscar();
        f.setVisible(true);
    }//GEN-LAST:event_jMnuiSeleccionarOtraSemanaActionPerformed

    public FrmCuadricula(RsSemanasDeTrabajo nueva_semana) {
        initComponents();
        semanas=nueva_semana;
    }
    
    private SemanaDeTrabajo punteroDeSemana=null;
    private RsSemanasDeTrabajo semanas=null;
    public abstract void eveClickSemana(RsDiasDeTrabajo nuevos_dias_de_trabajo);
    private class FrmBuscar extends FrmBuscarSemanas{

        public FrmBuscar(){
            super(semanas);
        }
        
        @Override
        public void eveItemSeleccionado(String datos) {
            
            punteroDeSemana=semanas.get(new SemanaDeTrabajo(datos));
//            System.out.println("datos="+punteroDeSemana.toString());
            this.setTotalDeHoras(punteroDeSemana.getTotalDeHoras());
            eveClickSemana(punteroDeSemana.getDiasSemanales());
        }

        @Override
        public void eveMostrarResultados() {
            //Saliendo
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuArchivo;
    private javax.swing.JMenuItem jMnuiGuardarSemana;
    private javax.swing.JMenuItem jMnuiSalir;
    private javax.swing.JMenuItem jMnuiSeleccionarOtraSemana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
