/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Datos;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jugador
 */
public class FrmCosturas extends javax.swing.JFrame {
    
    /**
     * Se usa en las busquedas y para proporcionar la informacion encontrada a los formularios.
     */
    private DiaDeTrabajo punteroDeRegistros=null;//new DiaDeTrabajo("0");
    
    
    private class frmModificarDiaDeTrabajo extends FrmModificarCosturas{
        
        public frmModificarDiaDeTrabajo(DiaDeTrabajo un_dia_de_trabajo){
            super(dias.get(un_dia_de_trabajo));
        }

        @Override
        public void eveGuardar(DiaDeTrabajo un_dia_de_trabajo_moificado) {
            punteroDeRegistros=un_dia_de_trabajo_moificado;
            try {
                dias.modificar(punteroDeRegistros);
                mostrarDatos();
            } catch (ModificarRsException ex) {
                System.out.println("frmModificarDiaDeTrabajo= " + ex.getMessage());
            }
        }
        
    }

    private RsDiasDeTrabajo dias=null;
    
    private void mostrarDatos(){
        try{
            jpDiaDeTrabajo1.setDia(punteroDeRegistros.getDia());
            jpDiaDeTrabajo1.setFecha(punteroDeRegistros.getFecha());
            jpDiaDeTrabajo1.setEntrada(punteroDeRegistros.getEntrada());
            jpDiaDeTrabajo1.setEntradaAmPm(punteroDeRegistros.getEntradaAmPm());
            jpDiaDeTrabajo1.setSalida(punteroDeRegistros.getSalida());
            jpDiaDeTrabajo1.setSalidaAmPm(punteroDeRegistros.getSalidaAmPm());
            jpDiaDeTrabajo1.setSubtotalDeHoras(punteroDeRegistros.getSubtotalDeHoras());
        }catch(Exception ex){
            
        }
    }
    
    public void setDias(RsDiasDeTrabajo nuevo_rs_dias){
        dias=nuevo_rs_dias;
        punteroDeRegistros=dias.get(0);
        mostrarDatos();
    }
    
    public FrmCosturas(RsDiasDeTrabajo nuevo_rs_dias) {
        initComponents();
        dias=new RsDiasDeTrabajo();
        punteroDeRegistros=dias.get(0);
        mostrarDatos();
    }
    
    public RsDiasDeTrabajo getDias(){
        return dias;
    }
    
    /**
     * Creates new form FrmCosturas
     */
    public FrmCosturas() {
        initComponents();
        
        try{
            rsSemanas.leer();
            dias=rsSemanas.get(0).getDiasSemanales();
            System.out.println("Total de horas " + dias.getTotalDeHoras());
        }catch(Exception e){
            dias=new RsDiasDeTrabajo();
            System.out.println("Cargando los dias sin datos.\n" + e.getMessage());
        }
        punteroDeRegistros=dias.get(dias.Size()-1);//Se muestra el ultimo.
        
        mostrarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnNuevo = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnVerCuadricula = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jpDiaDeTrabajo1 = new Datos.jpDiaDeTrabajo();
        jBtnBuscar = new javax.swing.JButton();
        jBtnSeleccionarOtraSemana = new javax.swing.JButton();
        jBtnNuevaSemana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costuras");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setToolTipText("");
        jBtnGuardar.setEnabled(false);
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jBtnModificar.setText("Modificar");
        jBtnModificar.setToolTipText("");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jBtnVerCuadricula.setText("Ver cuadricula");
        jBtnVerCuadricula.setToolTipText("");
        jBtnVerCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerCuadriculaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVerCuadricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 60, -1));
        getContentPane().add(jpDiaDeTrabajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, -1));

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jBtnSeleccionarOtraSemana.setText("Seleccionar otra semana");
        jBtnSeleccionarOtraSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeleccionarOtraSemanaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSeleccionarOtraSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jBtnNuevaSemana.setText("Nueva semana");
        jBtnNuevaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevaSemanaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNuevaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 340, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
//        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        jpDiaDeTrabajo1.limpiar();
        jBtnGuardar.setEnabled(true);
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        DiaDeTrabajo unDia=new DiaDeTrabajo();
        unDia.setDia(jpDiaDeTrabajo1.getDia());
        unDia.setFecha(jpDiaDeTrabajo1.getFecha());
        unDia.setEntrada(jpDiaDeTrabajo1.getEntrada());
        System.out.println("jpDiaDeTrabajo1.getEntradaAmPm()="+jpDiaDeTrabajo1.getEntradaAmPm());
        unDia.setEntradaAmPm(jpDiaDeTrabajo1.getEntradaAmPm());
        unDia.setSalida(jpDiaDeTrabajo1.getSalida());
        unDia.setSalidaAmPm(jpDiaDeTrabajo1.getSalidaAmPm());
        unDia.setSubtotalDeHoras(jpDiaDeTrabajo1.getSubtotalDeHoras());
        dias.add(unDia);
        jBtnGuardar.setEnabled(false);
        
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void cargarDiaDeTrabajo(){
        punteroDeRegistros=new DiaDeTrabajo("0");
        punteroDeRegistros.setDia(jpDiaDeTrabajo1.getDia());
        punteroDeRegistros.setFecha(jpDiaDeTrabajo1.getFecha());
        punteroDeRegistros.setEntrada(jpDiaDeTrabajo1.getEntrada());
        punteroDeRegistros.setEntradaAmPm(jpDiaDeTrabajo1.getEntradaAmPm());
        punteroDeRegistros.setSalida(jpDiaDeTrabajo1.getSalida());
        punteroDeRegistros.setSalidaAmPm(jpDiaDeTrabajo1.getSalidaAmPm());
        punteroDeRegistros.setSubtotalDeHoras(jpDiaDeTrabajo1.getSubtotalDeHoras());
    }
    
    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        cargarDiaDeTrabajo();
        frmModificarDiaDeTrabajo frmModificar=new frmModificarDiaDeTrabajo(punteroDeRegistros);
        frmModificar.setVisible(true);
//        jBtnModificar.setEnabled(false);
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private class FrmBusquedas extends FrmBuscarDias{
        public FrmBusquedas(){
            super(dias);
        }

        @Override
        public void eveItemSeleccionado(DiaDeTrabajo un_dia_de_trabajo_seleccionado) {
            System.out.println("un_dia_de_trabajo_seleccionado="+un_dia_de_trabajo_seleccionado);
            try {
                punteroDeRegistros=dias.buscar(un_dia_de_trabajo_seleccionado);
            } catch (BuscarRsException ex) {
                Logger.getLogger(FrmCosturas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jpDiaDeTrabajo1.setDia(punteroDeRegistros.getDia());
            jpDiaDeTrabajo1.setFecha(punteroDeRegistros.getFecha());
            jpDiaDeTrabajo1.setEntrada(punteroDeRegistros.getEntrada());
            jpDiaDeTrabajo1.setEntradaAmPm(punteroDeRegistros.getEntradaAmPm());
            jpDiaDeTrabajo1.setSalida(punteroDeRegistros.getSalida());
            jpDiaDeTrabajo1.setSalidaAmPm(punteroDeRegistros.getSalidaAmPm());
            jpDiaDeTrabajo1.setSubtotalDeHoras(punteroDeRegistros.getSubtotalDeHoras());
        }
        
    }
    
    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
//        jBtnModificar.setEnabled(true);
        FrmBusquedas frmBusqueda=new FrmBusquedas();
        frmBusqueda.setVisible(true);
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private RsSemanasDeTrabajo rsSemanas=new RsSemanasDeTrabajo();
//    this.
    private class FrmTabla extends FrmCuadricula{

        public FrmTabla(){
            super(rsSemanas);
        }
        
        @Override
        public void eveguardarSemana() {
            SemanaDeTrabajo semana=null;
            semana=new SemanaDeTrabajo();
            semana.setDiasSemanales(dias);
            semana.setFechaInicial(dias.get(0).getFecha());
            semana.setFechaFinal(dias.get(dias.Size()-1).getFecha());
            System.out.println("dias.getTotalDeHoras()= "+dias.getTotalDeHoras());
            System.out.println("semana="+semana.getTotalDeHoras());
            semana.setTotalDeHoras(dias.getTotalDeHoras());
            if(rsSemanas.existe(semana)==false){
                rsSemanas.add(semana);
                rsSemanas.escribir();
            }else{
                try {
                    rsSemanas.modificar(semana);
                    rsSemanas.escribir();
                } catch (ModificarRsException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
        
        @Override
        public void eveClickSemana(RsDiasDeTrabajo nuevos_dias_de_trabajo) {
            dias=nuevos_dias_de_trabajo;
            punteroDeRegistros=dias.get(0);//Se muestra el primer dia de la semana.
            mostrarDatos();
        }
        
    }
    
    private void jBtnVerCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerCuadriculaActionPerformed
        FrmTabla frmTabla=new FrmTabla();
        frmTabla.setVisible(true);
        try {
            frmTabla.setTableModel(this.dias.getCuadricula());
        } catch (getCuadriculaException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jBtnVerCuadriculaActionPerformed

  
    
    private class FrmBuscarUnaSemana extends FrmBuscarSemanas{

        public FrmBuscarUnaSemana(){
            super(rsSemanas);
        }
        
        private SemanaDeTrabajo punteroDeSemana=null;
        
        @Override
        public void eveMostrarResultados() {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void eveItemSeleccionado(String datos) {
            try {
                punteroDeSemana=rsSemanas.buscar(new SemanaDeTrabajo(datos));
                System.out.println("punteroDeSemana.getTotalDeHoras()= "+punteroDeSemana.getTotalDeHoras());
                this.setTotalDeHoras(punteroDeSemana.getTotalDeHoras()+"");
            } catch (BuscarRsException ex) {
                Logger.getLogger(FrmCosturas.class.getName()).log(Level.SEVERE, null, ex);
            }
            dias=punteroDeSemana.getDiasSemanales();
            mostrarDatos();
        }
        
    }
    
    private void jBtnSeleccionarOtraSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeleccionarOtraSemanaActionPerformed
        FrmBuscarUnaSemana OtrasSemanas=new FrmBuscarUnaSemana();
        OtrasSemanas.setVisible(true);
    }//GEN-LAST:event_jBtnSeleccionarOtraSemanaActionPerformed

    private void jBtnNuevaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevaSemanaActionPerformed
        dias=new RsDiasDeTrabajo();
    }//GEN-LAST:event_jBtnNuevaSemanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCosturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCosturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCosturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCosturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmCosturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevaSemana;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSeleccionarOtraSemana;
    private javax.swing.JButton jBtnVerCuadricula;
    private Datos.jpDiaDeTrabajo jpDiaDeTrabajo1;
    // End of variables declaration//GEN-END:variables
}
