/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Datos;

/**
 *Permite modificaficar la informacion.
 * @author Jugador
 * 
 */
public abstract class FrmModificarCosturas extends javax.swing.JFrame {

    private DiaDeTrabajo unDia=null;
    /**
     * Creates new form FrmModificarCosturas
     */
    public FrmModificarCosturas(DiaDeTrabajo un_dia_de_trabajo_para_modificar) {
        initComponents();
        unDia=un_dia_de_trabajo_para_modificar;
//        try{
            jpDiaDeTrabajo1.setDia(unDia.getDia());
            jpDiaDeTrabajo1.setFecha(unDia.getFecha());
            jpDiaDeTrabajo1.setEntrada(unDia.getEntrada());
            jpDiaDeTrabajo1.setEntradaAmPm(unDia.getEntradaAmPm());
            jpDiaDeTrabajo1.setSalida(unDia.getSalida());
            jpDiaDeTrabajo1.setSalidaAmPm(unDia.getSalidaAmPm());
            jpDiaDeTrabajo1.setSubtotalDeHoras(unDia.getSubtotalDeHoras());
//        }catch(Exception ex){
//        
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGuardar = new javax.swing.JButton();
        jpDiaDeTrabajo1 = new Datos.jpDiaDeTrabajo();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setToolTipText("");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jpDiaDeTrabajo1.setEnableFecha(false);
        getContentPane().add(jpDiaDeTrabajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public abstract void eveGuardar(DiaDeTrabajo un_dia_de_trabajo_moificado);
    
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        
        unDia.setDia(jpDiaDeTrabajo1.getDia());
        unDia.setFecha(jpDiaDeTrabajo1.getFecha());
        unDia.setEntrada(jpDiaDeTrabajo1.getEntrada());
        unDia.setEntradaAmPm(jpDiaDeTrabajo1.getEntradaAmPm());
        unDia.setSalida(jpDiaDeTrabajo1.getSalida());
        unDia.setSalidaAmPm(jpDiaDeTrabajo1.getSalidaAmPm());
        unDia.setSubtotalDeHoras(jpDiaDeTrabajo1.getSubtotalDeHoras());
        eveGuardar(unDia);
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnSalir;
    private Datos.jpDiaDeTrabajo jpDiaDeTrabajo1;
    // End of variables declaration//GEN-END:variables
}
