/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Datos;

/**
 *
 * @author Jugador
 */
public abstract class FrmSemanasDeTrabajo extends javax.swing.JFrame {
    
//    private FrmCosturas frmCosturas=null;
    private RsSemanasDeTrabajo semanas=null;
    
    public FrmSemanasDeTrabajo(RsSemanasDeTrabajo nueva_semana) {
        initComponents();
        semanas=nueva_semana;
    }

    /**
     * Creates new form FrmPanel
     */
    public FrmSemanasDeTrabajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnVerSemanaActual = new javax.swing.JButton();
        jBtnElegirUnaSemana = new javax.swing.JButton();
        jBtnSalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnVerSemanaActual.setText("Ver semana actual");
        jBtnVerSemanaActual.setEnabled(false);
        jBtnVerSemanaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerSemanaActualActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVerSemanaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jBtnElegirUnaSemana.setText("Elegir una semana");
        jBtnElegirUnaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElegirUnaSemanaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnElegirUnaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jBtnSalir2.setText("Salir");
        jBtnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalir2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalir2ActionPerformed

    private void jBtnVerSemanaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerSemanaActualActionPerformed
        try{
//            frmCosturas=new FrmCosturas(semanas.get(semanas.Size()-1).getDiasSemanales());
//            frmCosturas.setVisible(true);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jBtnVerSemanaActualActionPerformed

    private SemanaDeTrabajo punteroDeSemana=null;
    
    public abstract void eveClickItem(RsDiasDeTrabajo nuevos_dias_de_trabajo);
    public abstract void eveSaliendoDeLaLista();
    
    private class FrmBuscar extends FrmBuscarSemanas{

        public FrmBuscar(){
            super(semanas);
        }
        
        @Override
        public void eveItemSeleccionado(String datos) {
            
            punteroDeSemana=semanas.get(new SemanaDeTrabajo(datos));
//            System.out.println("datos="+punteroDeSemana.toString());
            eveClickItem(punteroDeSemana.getDiasSemanales());
        }

        @Override
        public void eveMostrarResultados() {
            eveSaliendoDeLaLista();
        }
        
    }
    
    public abstract void eveMostrandoLista();
    
    private void jBtnElegirUnaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElegirUnaSemanaActionPerformed
        FrmBuscar fBusqueda=new FrmBuscar();
        eveMostrandoLista();
        fBusqueda.setVisible(true);
    }//GEN-LAST:event_jBtnElegirUnaSemanaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElegirUnaSemana;
    private javax.swing.JButton jBtnSalir2;
    private javax.swing.JButton jBtnVerSemanaActual;
    // End of variables declaration//GEN-END:variables
}
