/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ia;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Jugador
 */
public class Grafica extends javax.swing.JPanel {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        this.setBounds(0, 0, 300, 300);
    }
    
    private int []medida;
    private int valorYNuevo=20;
    private int valorYViejo=20;
    
    
    public void setPromedio(int []mNumeros){
        medida=mNumeros;
        repaint();
    }
    
    @Override
    public void paint(Graphics g){
        g.setColor(Color.GREEN);
        try{
            for(int i=0; i<medida.length; i++){
                valorYViejo=valorYNuevo;
                if(i==0){
                    g.drawLine(0, valorYNuevo,98, -medida[i]/100);
                }else{
                    g.drawLine(valorYViejo, valorYNuevo, 98, -medida[i]/100);
                }
                valorYNuevo++;
            }
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
