/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exagonal;

import java.util.ArrayList;
import java.util.EventListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Jugador
 */
public class Casa extends Edificio {
    public static int precioEnOro=100;
    
    public static int precioEnMadera=100;
    
    public static int precioEnAlimentos=100;
    
    public static int precioEnPiedra=75;
  
    public static ArrayList<Casa> rsCasas=new ArrayList<Casa>();
    
    public static int maxDelProgressBar=100;
    
    private static void addCasa(Casa nuevo){
        for(int i=0; i<rsCasas.size(); i++){
            if(rsCasas.get(i).getNumeroDeInstancia()==nuevo.getNumeroDeInstancia()){
//                System.out.println(rsTerritorios.get(i).getNombre()+" modificado por " + nuevo.getNombre());
                rsCasas.remove(i);
                rsCasas.add(nuevo);
                
                return;//Salta de una sola vez.
            }
        }
        rsCasas.add(nuevo);
//        System.out.println("Nueva casa agregada "+rsCasas.size());
    }
    
    public static int ConsumoDeComida(){
        return AbstractTerritorio.poblacion*2;
    }
    
    @Override
    public void generandoRecursos() {
        setRecursosEnGenerados(getRecursosEnGenerados()+this.getCantidadDeRecursosHaGenerar());
        recursosGeneradosPorTodasLasCasas+=getRecursosEnGenerados();
        addCasa(this);//Actualiza las modificasiones en el ArrayList.
    }

    public static int habitantesPorCasa=4;
//    /**
//     * Permite evitar que aparescan 4 pobladores sin haber creado ninguna casa.
//     * Posiblemente se debe a que el class es llamado para algunas funciones nivel static o globales.
//     */
//    private static boolean poblacinInicial=false;
    public static int recursosGeneradosPorTodasLasCasas=0;
    /**
     * Creates new form Casa
     */
    public Casa() {
//        super();
        initComponents();
        setNombre("Casa" + this.getNumeroDeInstancia());
        this.setImagen(AbstractTerritorio.imagenes.getCasa());
        AbstractTerritorio.poblacion+=habitantesPorCasa;//Cada vez que se crea una casa la poblacion aumenta a 4.
        this.setMax(maxDelProgressBar);
        this.setCantidadDeRecursosHaGenerar(5);
        this.setCantidadDeRecursosHaGenerar(5);
        addCasa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void eveEventosAgregados() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
