/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exagonal;

/**
 *
 * @author Jugador
 */
public class Etiqueta extends javax.swing.JPanel {

    
    private int vMax=0;
    
    public void setMax(int nuevo_maximo){
        vMax=nuevo_maximo;
        jProgressBar1.setMaximum(vMax);
    }
    
    public int getMax(){
        return jProgressBar1.getMaximum();
    }


    private int valor=0;

    public void setProgress(int nuevo_progreso){
        valor=nuevo_progreso;//jProgressBar1.getValue()+1;
        jProgressBar1.setValue(valor);
    }
    
    private String texto="Etiqueta";
    public void setTexto(String nuevo_texto){
        texto=nuevo_texto;
        this.jLbAlimentos.setText(texto);
    }
    public String getTexto(){
        return texto;
    }
    
    /**
     * Creates new form Etiqueta
     */
    public Etiqueta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbAlimentos = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setPreferredSize(new java.awt.Dimension(150, 47));
        setLayout(null);

        jLbAlimentos.setBackground(new java.awt.Color(204, 255, 204));
        jLbAlimentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbAlimentos.setText("Alimentos");
        jLbAlimentos.setOpaque(true);
        add(jLbAlimentos);
        jLbAlimentos.setBounds(0, 0, 150, 30);
        add(jProgressBar1);
        jProgressBar1.setBounds(0, 30, 150, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbAlimentos;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
