/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exagonal;

import java.util.ArrayList;

/**
 *
 * @author Jugador
 */
public class Farm extends Edificio {

    public static ArrayList<Farm> rsFarms=new ArrayList<Farm>();
    
    private static void add(Farm nuevo){
        for(int i=0; i<rsFarms.size(); i++){
            if(rsFarms.get(i).getNumeroDeInstancia()==nuevo.getNumeroDeInstancia()){
                System.out.println(rsFarms.get(i).getNombre()+" modificado por " + nuevo.getNombre());
                rsFarms.remove(i);
                rsFarms.add(nuevo);
                System.out.println("Recursos "+rsFarms.get(i).getRecursosEnGenerados() + "; size="+rsFarms.size());
                return;//Salta de una sola vez.
            }
        }
        rsFarms.add(nuevo);
    }
    
    public static int recursosGeneradosPorTodasLasGranjas=0;
    
    @Override
    public void generandoRecursos() {
        
        setRecursosEnGenerados(getRecursosEnGenerados()+this.getCantidadDeRecursosHaGenerar());
        recursosGeneradosPorTodasLasGranjas=getRecursosEnGenerados();
        add(this);
        
    }
    /**
     * Creates new form Granja
     */
    public Farm() {
        initComponents();
        setNombre("Granja" + this.getNumeroDeInstancia());
        setImagen(AbstractTerritorio.imagenes.getGranja());
        add(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
