/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exagonal;

/**
 *
 * @author Jugador
 */
public abstract class FrmComprarTerritorio extends javax.swing.JFrame {

    public FrmComprarTerritorio(Territorio nuevo_territorio) {
        initComponents();
        territorio=nuevo_territorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbTerritorioSinComprar = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jLbPrecio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(355, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jLbTerritorioSinComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exagonal/dirt_12.png"))); // NOI18N
        jLbTerritorioSinComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbTerritorioSinComprarMouseClicked(evt);
            }
        });
        getContentPane().add(jLbTerritorioSinComprar);
        jLbTerritorioSinComprar.setBounds(10, 10, 120, 130);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(80, 170, 80, 25);

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar1);
        btnCancelar1.setBounds(180, 170, 80, 25);

        jLbPrecio.setText("0");
        getContentPane().add(jLbPrecio);
        jLbPrecio.setBounds(150, 100, 130, 16);

        jLabel2.setText("¿Desea comprar el territorio?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 170, 16);

        jLbNombre.setText("0");
        getContentPane().add(jLbNombre);
        jLbNombre.setBounds(150, 60, 150, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbTerritorioSinComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbTerritorioSinComprarMouseClicked
//        this.rbtnCasa.setSelected(true);
    }//GEN-LAST:event_jLbTerritorioSinComprarMouseClicked

    public abstract void eveAceptar(Territorio territorio_comprado);
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        territorio.setComprado(true);
        eveAceptar(territorio);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public abstract void eveCancelar();
    
    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        eveCancelar();
        this.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private Territorio territorio;
    public void setTerritorio(Territorio nuevo_territorio){
        territorio=nuevo_territorio;
        this.jLbNombre.setText(territorio.getNombre() + territorio.getNumeroDeInstancia());
        this.jLbPrecio.setText(""+100);
    }
    public Territorio getTerritorio(){
        return territorio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JLabel jLbPrecio;
    private javax.swing.JLabel jLbTerritorioSinComprar;
    // End of variables declaration//GEN-END:variables
}
