/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exagonal;

import static Exagonal.Territorio.cantidadDeInstancias;
import java.awt.Point;

/**
 *
 * @author Jugador
 */
public class FrmMapaExagonal extends javax.swing.JFrame {

    private Eventos vEventos=new Eventos();
    /**
     * Creates new form FrmMapaExagonal
     */
    public FrmMapaExagonal() {
        initComponents();
        Territorio.setEventosParaTodasLasInstancias(vEventos);
        this.territorio1.setEventos(vEventos);
        territorio2.setEventos(vEventos);
        territorio3.setEventos(vEventos);
        territorio4.setEventos(vEventos);
        territorio5.setEventos(vEventos);
        territorio6.setEventos(vEventos);
//        territorio7.setEventos(vEventos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        territorio1 = new Exagonal.Territorio();
        territorio2 = new Exagonal.Territorio();
        territorio3 = new Exagonal.Territorio();
        territorio4 = new Exagonal.Territorio();
        territorio5 = new Exagonal.Territorio();
        territorio6 = new Exagonal.Territorio();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        territorio1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio1MouseMoved(evt);
            }
        });
        getContentPane().add(territorio1);
        territorio1.setBounds(180, 100, 120, 140);

        territorio2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio2MouseMoved(evt);
            }
        });
        getContentPane().add(territorio2);
        territorio2.setBounds(0, 0, 120, 140);

        territorio3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio3MouseMoved(evt);
            }
        });
        getContentPane().add(territorio3);
        territorio3.setBounds(120, 0, 120, 140);

        territorio4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio4MouseMoved(evt);
            }
        });
        getContentPane().add(territorio4);
        territorio4.setBounds(60, 100, 120, 140);

        territorio5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio5MouseMoved(evt);
            }
        });
        getContentPane().add(territorio5);
        territorio5.setBounds(240, 0, 120, 140);

        territorio6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                territorio6MouseMoved(evt);
            }
        });
        getContentPane().add(territorio6);
        territorio6.setBounds(300, 100, 120, 140);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 90, 77, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detectar(){
//        for (int i=0; i<Territorio.rsTerritorios.size(); i++){
//            if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true){
//                 this.setTitle("Territorio seleccionado " + Territorio.rsTerritorios.get(i).instanciaNumero);
//            }else{
//                System.out.println("No colicion");
//            }
//        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        this.setTitle("Cantidad de territorios " + Territorio.rsTerritorios.size());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void territorio2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio2MouseMoved
        detectar();
    }//GEN-LAST:event_territorio2MouseMoved

    private void territorio3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio3MouseMoved
        detectar();
    }//GEN-LAST:event_territorio3MouseMoved

    private void territorio4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio4MouseMoved
        detectar();
    }//GEN-LAST:event_territorio4MouseMoved

    private void territorio1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio1MouseMoved
        detectar();
    }//GEN-LAST:event_territorio1MouseMoved

    private void territorio6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio6MouseMoved
       detectar();
    }//GEN-LAST:event_territorio6MouseMoved

    private void territorio5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_territorio5MouseMoved
        detectar();
    }//GEN-LAST:event_territorio5MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMapaExagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMapaExagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMapaExagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMapaExagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMapaExagonal().setVisible(true);
            }
        });
    }
    
    class Eventos extends AbstractDoubleClick{
        @Override
        public void eveClick(int x, int y, Point puntoXY) {
            System.out.println("Click");
        }

        @Override
        public void eveDobleClick(int x, int y, Point puntoXY) {
            //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        @Override
        public void mousePressed() {
//            System.out.println("Numero de instancia " + instanciaNumero + "; cantiad de instancias " + cantidadDeInstancias);
        }

        @Override
        public void mouseMoviendose() {
            for(int i=0; i<Territorio.rsTerritorios.size(); i++){
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==territorio1.estaSeleccionado() && Territorio.rsTerritorios.get(i).instanciaNumero==territorio1.instanciaNumero){
                    System.out.println("El puntero esta en 1 " + Territorio.rsTerritorios.get(i).instanciaNumero );
                    break;
                }
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true && Territorio.rsTerritorios.get(i).instanciaNumero==territorio2.instanciaNumero){
                    System.out.println("El puntero esta en 2 " + Territorio.rsTerritorios.get(i).instanciaNumero );
                    break;
                }
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true && Territorio.rsTerritorios.get(i).instanciaNumero==territorio3.instanciaNumero){
                    setTitle("El puntero esta en 3") ;//+ Territorio.rsTerritorios.get(i).instanciaNumero ); + Territorio.rsTerritorios.get(i).instanciaNumero );
                    break;
                }
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true){
                    setTitle("El puntero esta en 4") ;//+ Territorio.rsTerritorios.get(i).instanciaNumero ); + Territorio.rsTerritorios.get(i).instanciaNumero );
//                    break;
                }
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true){
                    setTitle("El puntero esta en 5") ;//+ Territorio.rsTerritorios.get(i).instanciaNumero ); + Territorio.rsTerritorios.get(i).instanciaNumero );
//                    break;
                }
                if(Territorio.rsTerritorios.get(i).estaSeleccionado()==true){
                    setTitle("El puntero esta en 6") ;//+ Territorio.rsTerritorios.get(i).instanciaNumero ); + Territorio.rsTerritorios.get(i).instanciaNumero );
//                    break;
                }
//                if(Territorio.rsTerritorios.get(i).instanciaNumero==territorio7.instanciaNumero){
//                    setTitle("El puntero esta en " + Territorio.rsTerritorios.get(i).instanciaNumero );
//                    break;
//                }
            }
        }

        @Override
        public void mouseArrastrastrado() {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private Exagonal.Territorio territorio1;
    private Exagonal.Territorio territorio2;
    private Exagonal.Territorio territorio3;
    private Exagonal.Territorio territorio4;
    private Exagonal.Territorio territorio5;
    private Exagonal.Territorio territorio6;
    // End of variables declaration//GEN-END:variables
}
