/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exagonal;

import java.awt.Point;

/**
 *
 * @author Jugador
 */
public abstract class FrmMenu extends javax.swing.JFrame {
    
    
    
    
    
    
    

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setVisible(true);
        this.setLocation(300,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        rbtnCasa = new javax.swing.JRadioButton();
        rbtnGranja = new javax.swing.JRadioButton();
        rbtnMina = new javax.swing.JRadioButton();
        jLbMina = new javax.swing.JLabel();
        jLbCasa = new javax.swing.JLabel();
        jLbFarm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones de construccion");
        setPreferredSize(new java.awt.Dimension(520, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Elija el edificio que desea construir.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 350, 25);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(250, 270, 80, 25);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(150, 270, 80, 25);

        buttonGroup1.add(rbtnCasa);
        rbtnCasa.setText("Casa");
        getContentPane().add(rbtnCasa);
        rbtnCasa.setBounds(30, 185, 100, 40);

        buttonGroup1.add(rbtnGranja);
        rbtnGranja.setText("Granja");
        getContentPane().add(rbtnGranja);
        rbtnGranja.setBounds(220, 210, 100, 25);

        buttonGroup1.add(rbtnMina);
        rbtnMina.setText("Mina");
        getContentPane().add(rbtnMina);
        rbtnMina.setBounds(390, 210, 101, 25);

        jLbMina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exagonal/medieval_mine.png"))); // NOI18N
        jLbMina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbMinaMouseClicked(evt);
            }
        });
        getContentPane().add(jLbMina);
        jLbMina.setBounds(370, 70, 120, 130);

        jLbCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exagonal/medieval_farm.png"))); // NOI18N
        jLbCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbCasaMouseClicked(evt);
            }
        });
        getContentPane().add(jLbCasa);
        jLbCasa.setBounds(20, 60, 120, 130);

        jLbFarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exagonal/medieval_windmill.png"))); // NOI18N
        jLbFarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbFarmMouseClicked(evt);
            }
        });
        getContentPane().add(jLbFarm);
        jLbFarm.setBounds(210, 70, 120, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 1) Construir casa.
     * 2) Construir granja.
     * 3) Construir mina.
     * @param tipo_de_edificio Un numero del 1 al 3 que indica que tipo de edificio se construirá.
     */
    public abstract void eveAceptar(int tipo_de_edificio);
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        eveAceptar(getNumeroDeEdificio());
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    public int getNumeroDeEdificio(){
        if(rbtnCasa.isSelected()==true){ return 1;}
        if(rbtnGranja.isSelected()==true){ return 2;}
        if(rbtnMina.isSelected()==true){ return 3;}
        return 0;
    }
    
    public abstract void eveCancelar();
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       eveCancelar();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jLbCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCasaMouseClicked
        this.rbtnCasa.setSelected(true);
    }//GEN-LAST:event_jLbCasaMouseClicked

    private void jLbFarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbFarmMouseClicked
        rbtnGranja.setSelected(true);
    }//GEN-LAST:event_jLbFarmMouseClicked

    private void jLbMinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbMinaMouseClicked
        rbtnMina.setSelected(true);
    }//GEN-LAST:event_jLbMinaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbCasa;
    private javax.swing.JLabel jLbFarm;
    private javax.swing.JLabel jLbMina;
    private javax.swing.JRadioButton rbtnCasa;
    private javax.swing.JRadioButton rbtnGranja;
    private javax.swing.JRadioButton rbtnMina;
    // End of variables declaration//GEN-END:variables
}
