/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exagonal;

import java.util.ArrayList;

/**
 *
 * @author Jugador
 */
public class Mina extends Edificio {

    public static int maxDelProgressBar=100;
    public static int recursosGeneradosPorTodasLasMinas=0;
    
    public static ArrayList<Mina> rsMinas=new ArrayList<Mina>();
    
    private static void addMina(Mina nuevo){
        for(int i=0; i<rsMinas.size(); i++){
            if(rsMinas.get(i).getNumeroDeInstancia()==nuevo.getNumeroDeInstancia()){
//                System.out.println(rsTerritorios.get(i).getNombre()+" modificado por " + nuevo.getNombre());
                rsMinas.remove(i);
                rsMinas.add(nuevo);
                
                return;//Salta de una sola vez.
            }
        }
        rsMinas.add(nuevo);
//        System.out.println("Nueva casa agregada "+rsCasas.size());
    }
    
    /**
     * Creates new form Mina
     */
    public Mina() {
        super();
        initComponents();
        this.setNombre("Mina" + this.getNumeroDeInstancia());
        setImagen(AbstractTerritorio.imagenes.getMina());
        this.setMax(maxDelProgressBar);
        addMina(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void generandoRecursos() {
        setRecursosEnGenerados(getRecursosEnGenerados()+this.getCantidadDeRecursosHaGenerar());
        recursosGeneradosPorTodasLasMinas=getRecursosEnGenerados();
        addMina(this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
