/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exagonal;

import java.util.ArrayList;

/**
 *
 * @author Jugador
 */
public class Territorio extends AbstractTerritorio{
    
    public static int precioEnOro=100;
    
    public static int precioEnMadera=100;
    
    public static int precioEnAlimentos=100;
    
    public static int precioEnPiedra=100;

    public static ArrayList<AbstractTerritorio> rsTerritorios=new ArrayList<AbstractTerritorio>();
    
    private static void addTerritorio(AbstractTerritorio nuevo){
        for(int i=0; i<rsTerritorios.size(); i++){
            if(rsTerritorios.get(i).getNumeroDeInstancia()==nuevo.getNumeroDeInstancia()){
//                System.out.println(rsTerritorios.get(i).getNombre()+" modificado por " + nuevo.getNombre());
                rsTerritorios.remove(i);
                rsTerritorios.add(nuevo);
                
                return;//Salta de una sola vez.
            }
        }
        rsTerritorios.add(nuevo);
    }
    /**
     * Creates new form NewJPanel
     */
    public Territorio() {
        initComponents();
        addTerritorio(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(138, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void eveEventosAgregados() {
        addTerritorio(this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
