/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Propiedades;

/**
 *
 * @author Rafae
 */
public class FrmPrincipalEjemplo extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipalEjemplo
     */
    public FrmPrincipalEjemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLRespuesta = new javax.swing.JLabel();
        jBtnObtenerDatos = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRespuesta.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLRespuesta.setText("Respuesta");
        jLRespuesta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 42, 560, 28));

        jBtnObtenerDatos.setText("Obtener datos");
        jBtnObtenerDatos.addActionListener(formListener);
        getContentPane().add(jBtnObtenerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 98, -1, -1));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(formListener);
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 98, -1, -1));

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jBtnSalir) {
                FrmPrincipalEjemplo.this.jBtnSalirActionPerformed(evt);
            }
            else if (evt.getSource() == jBtnObtenerDatos) {
                FrmPrincipalEjemplo.this.jBtnObtenerDatosActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private class Datos extends FrmPropiedadesRapidas
    {

        @Override
        public void Evento_Aceptar(Modelo respuesta) {
            jLRespuesta.setText("Nombre: " + respuesta.Nombre.get() + 
                    ", velor: " + respuesta.Numero.get() );
        }
        
    }
    
    private void jBtnObtenerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObtenerDatosActionPerformed
        Datos frmDatos=new Datos();
        frmDatos.setVisible(true);
    }//GEN-LAST:event_jBtnObtenerDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnObtenerDatos;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLRespuesta;
    // End of variables declaration//GEN-END:variables
}
