/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ajedres;

/**
 *
 *
 */
public class BackUpDelTablero extends javax.swing.JFrame {

    /**
     * Creates new form BackUpDelTablero
     */
    public BackUpDelTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla_07 = new javax.swing.JLabel();
        casilla_00 = new javax.swing.JLabel();
        casilla_10 = new javax.swing.JLabel();
        casilla_20 = new javax.swing.JLabel();
        casilla_30 = new javax.swing.JLabel();
        casilla_40 = new javax.swing.JLabel();
        casilla_50 = new javax.swing.JLabel();
        casilla_60 = new javax.swing.JLabel();
        casilla_70 = new javax.swing.JLabel();
        casilla_01 = new javax.swing.JLabel();
        casilla_02 = new javax.swing.JLabel();
        casilla_03 = new javax.swing.JLabel();
        casilla_04 = new javax.swing.JLabel();
        casilla_05 = new javax.swing.JLabel();
        casilla_06 = new javax.swing.JLabel();
        casilla_17 = new javax.swing.JLabel();
        casilla_11 = new javax.swing.JLabel();
        casilla_12 = new javax.swing.JLabel();
        casilla_13 = new javax.swing.JLabel();
        casilla_14 = new javax.swing.JLabel();
        casilla_15 = new javax.swing.JLabel();
        casilla_16 = new javax.swing.JLabel();
        casilla_27 = new javax.swing.JLabel();
        casilla_21 = new javax.swing.JLabel();
        casilla_22 = new javax.swing.JLabel();
        casilla_23 = new javax.swing.JLabel();
        casilla_24 = new javax.swing.JLabel();
        casilla_25 = new javax.swing.JLabel();
        casilla_26 = new javax.swing.JLabel();
        casilla_37 = new javax.swing.JLabel();
        casilla_31 = new javax.swing.JLabel();
        casilla_32 = new javax.swing.JLabel();
        casilla_33 = new javax.swing.JLabel();
        casilla_34 = new javax.swing.JLabel();
        casilla_35 = new javax.swing.JLabel();
        casilla_36 = new javax.swing.JLabel();
        casilla_47 = new javax.swing.JLabel();
        casilla_41 = new javax.swing.JLabel();
        casilla_42 = new javax.swing.JLabel();
        casilla_43 = new javax.swing.JLabel();
        casilla_44 = new javax.swing.JLabel();
        casilla_45 = new javax.swing.JLabel();
        casilla_46 = new javax.swing.JLabel();
        casilla_57 = new javax.swing.JLabel();
        casilla_51 = new javax.swing.JLabel();
        casilla_52 = new javax.swing.JLabel();
        casilla_53 = new javax.swing.JLabel();
        casilla_54 = new javax.swing.JLabel();
        casilla_55 = new javax.swing.JLabel();
        casilla_56 = new javax.swing.JLabel();
        casilla_67 = new javax.swing.JLabel();
        casilla_61 = new javax.swing.JLabel();
        casilla_62 = new javax.swing.JLabel();
        casilla_63 = new javax.swing.JLabel();
        casilla_64 = new javax.swing.JLabel();
        casilla_65 = new javax.swing.JLabel();
        casilla_66 = new javax.swing.JLabel();
        casilla_77 = new javax.swing.JLabel();
        casilla_71 = new javax.swing.JLabel();
        casilla_72 = new javax.swing.JLabel();
        casilla_73 = new javax.swing.JLabel();
        casilla_74 = new javax.swing.JLabel();
        casilla_75 = new javax.swing.JLabel();
        casilla_76 = new javax.swing.JLabel();
        jRbtJugador1 = new javax.swing.JRadioButton();
        jRbtJugador2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casilla_07.setText("07");
        casilla_07.setToolTipText("");
        casilla_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_07, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 40));

        casilla_00.setText("00");
        casilla_00.setToolTipText("00");
        casilla_00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        casilla_10.setText("10");
        casilla_10.setToolTipText("01");
        casilla_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, 40));

        casilla_20.setText("20");
        casilla_20.setToolTipText("");
        casilla_20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 40));

        casilla_30.setText("30");
        casilla_30.setToolTipText("");
        casilla_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 40));

        casilla_40.setText("40");
        casilla_40.setToolTipText("");
        casilla_40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        casilla_50.setText("50");
        casilla_50.setToolTipText("");
        casilla_50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 40, 40));

        casilla_60.setText("60");
        casilla_60.setToolTipText("");
        casilla_60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 40, 40));

        casilla_70.setText("70");
        casilla_70.setToolTipText("");
        casilla_70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 40, 40));

        casilla_01.setText("01");
        casilla_01.setToolTipText("");
        casilla_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        casilla_02.setText("02");
        casilla_02.setToolTipText("");
        casilla_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        casilla_03.setText("03");
        casilla_03.setToolTipText("");
        casilla_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 40, 40));

        casilla_04.setText("04");
        casilla_04.setToolTipText("");
        casilla_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        casilla_05.setText("05");
        casilla_05.setToolTipText("");
        casilla_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 40));

        casilla_06.setText("06");
        casilla_06.setToolTipText("");
        casilla_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_06, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 40));

        casilla_17.setText("19");
        casilla_17.setToolTipText("");
        casilla_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 40, 40));

        casilla_11.setText("12");
        casilla_11.setToolTipText("");
        casilla_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        casilla_12.setText("14");
        casilla_12.setToolTipText("");
        casilla_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 40));

        casilla_13.setText("15");
        casilla_13.setToolTipText("");
        casilla_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 40, 40));

        casilla_14.setText("16");
        casilla_14.setToolTipText("");
        casilla_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, 40));

        casilla_15.setText("17");
        casilla_15.setToolTipText("");
        casilla_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 40, 40));

        casilla_16.setText("18");
        casilla_16.setToolTipText("");
        casilla_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 40, 40));

        casilla_27.setText("27");
        casilla_27.setToolTipText("");
        casilla_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 40, 40));

        casilla_21.setText("21");
        casilla_21.setToolTipText("");
        casilla_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 40));

        casilla_22.setText("22");
        casilla_22.setToolTipText("");
        casilla_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 40, 40));

        casilla_23.setText("23");
        casilla_23.setToolTipText("");
        casilla_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, 40));

        casilla_24.setText("24");
        casilla_24.setToolTipText("");
        casilla_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, 40));

        casilla_25.setText("25");
        casilla_25.setToolTipText("");
        casilla_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 40, 40));

        casilla_26.setText("26");
        casilla_26.setToolTipText("");
        casilla_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 40));

        casilla_37.setText("37");
        casilla_37.setToolTipText("");
        casilla_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 40, 40));

        casilla_31.setText("31");
        casilla_31.setToolTipText("");
        casilla_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 40));

        casilla_32.setText("32");
        casilla_32.setToolTipText("");
        casilla_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, 40));

        casilla_33.setText("33");
        casilla_33.setToolTipText("");
        casilla_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        casilla_34.setText("34");
        casilla_34.setToolTipText("");
        casilla_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 40));

        casilla_35.setText("35");
        casilla_35.setToolTipText("");
        casilla_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 40, 40));

        casilla_36.setText("36");
        casilla_36.setToolTipText("");
        casilla_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, 40));

        casilla_47.setText("47");
        casilla_47.setToolTipText("");
        casilla_47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 40));

        casilla_41.setText("41");
        casilla_41.setToolTipText("");
        casilla_41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 40, 40));

        casilla_42.setText("42");
        casilla_42.setToolTipText("");
        casilla_42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 40, 40));

        casilla_43.setText("43");
        casilla_43.setToolTipText("");
        casilla_43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 40));

        casilla_44.setText("44");
        casilla_44.setToolTipText("");
        casilla_44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 40));

        casilla_45.setText("45");
        casilla_45.setToolTipText("");
        casilla_45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 40, 40));

        casilla_46.setText("46");
        casilla_46.setToolTipText("");
        casilla_46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, 40));

        casilla_57.setText("57");
        casilla_57.setToolTipText("");
        casilla_57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 40, 40));

        casilla_51.setText("51");
        casilla_51.setToolTipText("");
        casilla_51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 40));

        casilla_52.setText("52");
        casilla_52.setToolTipText("");
        casilla_52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, 40));

        casilla_53.setText("53");
        casilla_53.setToolTipText("");
        casilla_53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 40, 40));

        casilla_54.setText("54");
        casilla_54.setToolTipText("");
        casilla_54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 40, 40));

        casilla_55.setText("55");
        casilla_55.setToolTipText("");
        casilla_55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 40));

        casilla_56.setText("56");
        casilla_56.setToolTipText("");
        casilla_56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_56, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 40, 40));

        casilla_67.setText("67");
        casilla_67.setToolTipText("");
        casilla_67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_67, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 40, 40));

        casilla_61.setText("61");
        casilla_61.setToolTipText("");
        casilla_61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 40, 40));

        casilla_62.setText("62");
        casilla_62.setToolTipText("");
        casilla_62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_62, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 40));

        casilla_63.setText("63");
        casilla_63.setToolTipText("");
        casilla_63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_63, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 40, 40));

        casilla_64.setText("64");
        casilla_64.setToolTipText("");
        casilla_64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_64, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 40, 40));

        casilla_65.setText("65");
        casilla_65.setToolTipText("");
        casilla_65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_65, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 40));

        casilla_66.setText("66");
        casilla_66.setToolTipText("");
        casilla_66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 40, 40));

        casilla_77.setText("77");
        casilla_77.setToolTipText("");
        casilla_77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_77, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 40, 40));

        casilla_71.setText("71");
        casilla_71.setToolTipText("");
        casilla_71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 40));

        casilla_72.setText("72");
        casilla_72.setToolTipText("");
        casilla_72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 40, 40));

        casilla_73.setText("73");
        casilla_73.setToolTipText("");
        casilla_73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_73, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 40));

        casilla_74.setText("74");
        casilla_74.setToolTipText("");
        casilla_74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_74, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, 40));

        casilla_75.setText("75");
        casilla_75.setToolTipText("");
        casilla_75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_75, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 40));

        casilla_76.setText("76");
        casilla_76.setToolTipText("");
        casilla_76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(casilla_76, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, 40));

        jRbtJugador1.setText("Jugador 1");
        getContentPane().add(jRbtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jRbtJugador2.setText("Jugador 2");
        getContentPane().add(jRbtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackUpDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackUpDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackUpDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackUpDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackUpDelTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casilla_00;
    private javax.swing.JLabel casilla_01;
    private javax.swing.JLabel casilla_02;
    private javax.swing.JLabel casilla_03;
    private javax.swing.JLabel casilla_04;
    private javax.swing.JLabel casilla_05;
    private javax.swing.JLabel casilla_06;
    private javax.swing.JLabel casilla_07;
    private javax.swing.JLabel casilla_10;
    private javax.swing.JLabel casilla_11;
    private javax.swing.JLabel casilla_12;
    private javax.swing.JLabel casilla_13;
    private javax.swing.JLabel casilla_14;
    private javax.swing.JLabel casilla_15;
    private javax.swing.JLabel casilla_16;
    private javax.swing.JLabel casilla_17;
    private javax.swing.JLabel casilla_20;
    private javax.swing.JLabel casilla_21;
    private javax.swing.JLabel casilla_22;
    private javax.swing.JLabel casilla_23;
    private javax.swing.JLabel casilla_24;
    private javax.swing.JLabel casilla_25;
    private javax.swing.JLabel casilla_26;
    private javax.swing.JLabel casilla_27;
    private javax.swing.JLabel casilla_30;
    private javax.swing.JLabel casilla_31;
    private javax.swing.JLabel casilla_32;
    private javax.swing.JLabel casilla_33;
    private javax.swing.JLabel casilla_34;
    private javax.swing.JLabel casilla_35;
    private javax.swing.JLabel casilla_36;
    private javax.swing.JLabel casilla_37;
    private javax.swing.JLabel casilla_40;
    private javax.swing.JLabel casilla_41;
    private javax.swing.JLabel casilla_42;
    private javax.swing.JLabel casilla_43;
    private javax.swing.JLabel casilla_44;
    private javax.swing.JLabel casilla_45;
    private javax.swing.JLabel casilla_46;
    private javax.swing.JLabel casilla_47;
    private javax.swing.JLabel casilla_50;
    private javax.swing.JLabel casilla_51;
    private javax.swing.JLabel casilla_52;
    private javax.swing.JLabel casilla_53;
    private javax.swing.JLabel casilla_54;
    private javax.swing.JLabel casilla_55;
    private javax.swing.JLabel casilla_56;
    private javax.swing.JLabel casilla_57;
    private javax.swing.JLabel casilla_60;
    private javax.swing.JLabel casilla_61;
    private javax.swing.JLabel casilla_62;
    private javax.swing.JLabel casilla_63;
    private javax.swing.JLabel casilla_64;
    private javax.swing.JLabel casilla_65;
    private javax.swing.JLabel casilla_66;
    private javax.swing.JLabel casilla_67;
    private javax.swing.JLabel casilla_70;
    private javax.swing.JLabel casilla_71;
    private javax.swing.JLabel casilla_72;
    private javax.swing.JLabel casilla_73;
    private javax.swing.JLabel casilla_74;
    private javax.swing.JLabel casilla_75;
    private javax.swing.JLabel casilla_76;
    private javax.swing.JLabel casilla_77;
    private javax.swing.JRadioButton jRbtJugador1;
    private javax.swing.JRadioButton jRbtJugador2;
    // End of variables declaration//GEN-END:variables
}
