/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ajedres;

/**
 *
 * @author Jugador
 */
public abstract class Tablero2 extends javax.swing.JPanel {

    
    public abstract void clickCasillaOrigen(Casilla nueva_casilla);
    public abstract void clickCasillaDestino(Casilla nueva_casilla); 
    private Casilla casilla=new Casilla();
    
    private void establecerRuta(int fila, int columna){
        Casilla.contarClicks();
        casilla.setFila(fila);
        casilla.setColumna(columna);
        if(Casilla.contadorDeSelecciones==1){
            this.clickCasillaOrigen(casilla);
        }
        if(Casilla.contadorDeSelecciones==2){
            this.clickCasillaDestino(casilla);
        }
    }
    /**
     * Creates new form Tablero2
     */
    public Tablero2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla_07 = new javax.swing.JLabel();
        casilla_00 = new javax.swing.JLabel();
        casilla_10 = new javax.swing.JLabel();
        casilla_20 = new javax.swing.JLabel();
        casilla_30 = new javax.swing.JLabel();
        casilla_40 = new javax.swing.JLabel();
        casilla_50 = new javax.swing.JLabel();
        casilla_60 = new javax.swing.JLabel();
        casilla_70 = new javax.swing.JLabel();
        casilla_01 = new javax.swing.JLabel();
        casilla_02 = new javax.swing.JLabel();
        casilla_03 = new javax.swing.JLabel();
        casilla_04 = new javax.swing.JLabel();
        casilla_05 = new javax.swing.JLabel();
        casilla_06 = new javax.swing.JLabel();
        casilla_17 = new javax.swing.JLabel();
        casilla_11 = new javax.swing.JLabel();
        casilla_12 = new javax.swing.JLabel();
        casilla_13 = new javax.swing.JLabel();
        casilla_14 = new javax.swing.JLabel();
        casilla_15 = new javax.swing.JLabel();
        casilla_16 = new javax.swing.JLabel();
        casilla_27 = new javax.swing.JLabel();
        casilla_21 = new javax.swing.JLabel();
        casilla_22 = new javax.swing.JLabel();
        casilla_23 = new javax.swing.JLabel();
        casilla_24 = new javax.swing.JLabel();
        casilla_25 = new javax.swing.JLabel();
        casilla_26 = new javax.swing.JLabel();
        casilla_37 = new javax.swing.JLabel();
        casilla_31 = new javax.swing.JLabel();
        casilla_32 = new javax.swing.JLabel();
        casilla_33 = new javax.swing.JLabel();
        casilla_34 = new javax.swing.JLabel();
        casilla_35 = new javax.swing.JLabel();
        casilla_36 = new javax.swing.JLabel();
        casilla_47 = new javax.swing.JLabel();
        casilla_41 = new javax.swing.JLabel();
        casilla_42 = new javax.swing.JLabel();
        casilla_43 = new javax.swing.JLabel();
        casilla_44 = new javax.swing.JLabel();
        casilla_45 = new javax.swing.JLabel();
        casilla_46 = new javax.swing.JLabel();
        casilla_57 = new javax.swing.JLabel();
        casilla_51 = new javax.swing.JLabel();
        casilla_52 = new javax.swing.JLabel();
        casilla_53 = new javax.swing.JLabel();
        casilla_54 = new javax.swing.JLabel();
        casilla_55 = new javax.swing.JLabel();
        casilla_56 = new javax.swing.JLabel();
        casilla_67 = new javax.swing.JLabel();
        casilla_61 = new javax.swing.JLabel();
        casilla_62 = new javax.swing.JLabel();
        casilla_63 = new javax.swing.JLabel();
        casilla_64 = new javax.swing.JLabel();
        casilla_65 = new javax.swing.JLabel();
        casilla_66 = new javax.swing.JLabel();
        casilla_77 = new javax.swing.JLabel();
        casilla_71 = new javax.swing.JLabel();
        casilla_72 = new javax.swing.JLabel();
        casilla_73 = new javax.swing.JLabel();
        casilla_74 = new javax.swing.JLabel();
        casilla_75 = new javax.swing.JLabel();
        casilla_76 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casilla_07.setBackground(new java.awt.Color(102, 102, 102));
        casilla_07.setText("07");
        casilla_07.setToolTipText("");
        casilla_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_07.setOpaque(true);
        add(casilla_07, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 40));

        casilla_00.setBackground(new java.awt.Color(255, 255, 255));
        casilla_00.setText("00");
        casilla_00.setToolTipText("00");
        casilla_00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_00.setOpaque(true);
        casilla_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_00MouseClicked(evt);
            }
        });
        add(casilla_00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        casilla_10.setBackground(new java.awt.Color(102, 102, 102));
        casilla_10.setText("10");
        casilla_10.setToolTipText("01");
        casilla_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_10.setOpaque(true);
        casilla_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_10MouseClicked(evt);
            }
        });
        add(casilla_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, 40));

        casilla_20.setBackground(new java.awt.Color(255, 255, 255));
        casilla_20.setText("20");
        casilla_20.setToolTipText("");
        casilla_20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_20.setOpaque(true);
        casilla_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_20MouseClicked(evt);
            }
        });
        add(casilla_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 40));

        casilla_30.setBackground(new java.awt.Color(102, 102, 102));
        casilla_30.setText("30");
        casilla_30.setToolTipText("");
        casilla_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_30.setOpaque(true);
        casilla_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_30MouseClicked(evt);
            }
        });
        add(casilla_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 40));

        casilla_40.setBackground(new java.awt.Color(255, 255, 255));
        casilla_40.setText("40");
        casilla_40.setToolTipText("");
        casilla_40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_40.setOpaque(true);
        casilla_40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_40MouseClicked(evt);
            }
        });
        add(casilla_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        casilla_50.setBackground(new java.awt.Color(102, 102, 102));
        casilla_50.setText("50");
        casilla_50.setToolTipText("");
        casilla_50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_50.setOpaque(true);
        casilla_50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_50MouseClicked(evt);
            }
        });
        add(casilla_50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 40, 40));

        casilla_60.setBackground(new java.awt.Color(255, 255, 255));
        casilla_60.setText("60");
        casilla_60.setToolTipText("");
        casilla_60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_60.setOpaque(true);
        casilla_60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_60MouseClicked(evt);
            }
        });
        add(casilla_60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 40, 40));

        casilla_70.setBackground(new java.awt.Color(102, 102, 102));
        casilla_70.setText("70");
        casilla_70.setToolTipText("");
        casilla_70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_70.setOpaque(true);
        casilla_70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_70MouseClicked(evt);
            }
        });
        add(casilla_70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 40, 40));

        casilla_01.setBackground(new java.awt.Color(102, 102, 102));
        casilla_01.setText("01");
        casilla_01.setToolTipText("");
        casilla_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_01.setOpaque(true);
        casilla_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla_01MouseClicked(evt);
            }
        });
        add(casilla_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        casilla_02.setBackground(new java.awt.Color(255, 255, 255));
        casilla_02.setText("02");
        casilla_02.setToolTipText("");
        casilla_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_02.setOpaque(true);
        add(casilla_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        casilla_03.setBackground(new java.awt.Color(102, 102, 102));
        casilla_03.setText("03");
        casilla_03.setToolTipText("");
        casilla_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_03.setOpaque(true);
        add(casilla_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 40, 40));

        casilla_04.setBackground(new java.awt.Color(255, 255, 255));
        casilla_04.setText("04");
        casilla_04.setToolTipText("");
        casilla_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_04.setOpaque(true);
        add(casilla_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        casilla_05.setBackground(new java.awt.Color(102, 102, 102));
        casilla_05.setText("05");
        casilla_05.setToolTipText("");
        casilla_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_05.setOpaque(true);
        add(casilla_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 40));

        casilla_06.setBackground(new java.awt.Color(255, 255, 255));
        casilla_06.setText("06");
        casilla_06.setToolTipText("");
        casilla_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_06.setOpaque(true);
        add(casilla_06, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 40));

        casilla_17.setBackground(new java.awt.Color(255, 255, 255));
        casilla_17.setText("17");
        casilla_17.setToolTipText("");
        casilla_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_17.setOpaque(true);
        add(casilla_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 40, 40));

        casilla_11.setBackground(new java.awt.Color(255, 255, 255));
        casilla_11.setText("11");
        casilla_11.setToolTipText("");
        casilla_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_11.setOpaque(true);
        add(casilla_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        casilla_12.setBackground(new java.awt.Color(102, 102, 102));
        casilla_12.setText("12");
        casilla_12.setToolTipText("");
        casilla_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_12.setOpaque(true);
        add(casilla_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 40));

        casilla_13.setBackground(new java.awt.Color(255, 255, 255));
        casilla_13.setText("13");
        casilla_13.setToolTipText("");
        casilla_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_13.setOpaque(true);
        add(casilla_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 40, 40));

        casilla_14.setBackground(new java.awt.Color(102, 102, 102));
        casilla_14.setText("14");
        casilla_14.setToolTipText("");
        casilla_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_14.setOpaque(true);
        add(casilla_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, 40));

        casilla_15.setBackground(new java.awt.Color(255, 255, 255));
        casilla_15.setText("15");
        casilla_15.setToolTipText("");
        casilla_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_15.setOpaque(true);
        add(casilla_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 40, 40));

        casilla_16.setBackground(new java.awt.Color(102, 102, 102));
        casilla_16.setText("16");
        casilla_16.setToolTipText("");
        casilla_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_16.setOpaque(true);
        add(casilla_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 40, 40));

        casilla_27.setBackground(new java.awt.Color(102, 102, 102));
        casilla_27.setText("27");
        casilla_27.setToolTipText("");
        casilla_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_27.setOpaque(true);
        add(casilla_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 40, 40));

        casilla_21.setBackground(new java.awt.Color(102, 102, 102));
        casilla_21.setText("21");
        casilla_21.setToolTipText("");
        casilla_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_21.setOpaque(true);
        add(casilla_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 40));

        casilla_22.setBackground(new java.awt.Color(255, 255, 255));
        casilla_22.setText("22");
        casilla_22.setToolTipText("");
        casilla_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_22.setOpaque(true);
        add(casilla_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 40, 40));

        casilla_23.setBackground(new java.awt.Color(102, 102, 102));
        casilla_23.setText("23");
        casilla_23.setToolTipText("");
        casilla_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_23.setOpaque(true);
        add(casilla_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, 40));

        casilla_24.setBackground(new java.awt.Color(255, 255, 255));
        casilla_24.setText("24");
        casilla_24.setToolTipText("");
        casilla_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_24.setOpaque(true);
        add(casilla_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, 40));

        casilla_25.setBackground(new java.awt.Color(102, 102, 102));
        casilla_25.setText("25");
        casilla_25.setToolTipText("");
        casilla_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_25.setOpaque(true);
        add(casilla_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 40, 40));

        casilla_26.setBackground(new java.awt.Color(255, 255, 255));
        casilla_26.setText("26");
        casilla_26.setToolTipText("");
        casilla_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_26.setOpaque(true);
        add(casilla_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 40));

        casilla_37.setBackground(new java.awt.Color(255, 255, 255));
        casilla_37.setText("37");
        casilla_37.setToolTipText("");
        casilla_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_37.setOpaque(true);
        add(casilla_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 40, 40));

        casilla_31.setBackground(new java.awt.Color(255, 255, 255));
        casilla_31.setText("31");
        casilla_31.setToolTipText("");
        casilla_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_31.setOpaque(true);
        add(casilla_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 40));

        casilla_32.setBackground(new java.awt.Color(102, 102, 102));
        casilla_32.setText("32");
        casilla_32.setToolTipText("");
        casilla_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_32.setOpaque(true);
        add(casilla_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, 40));

        casilla_33.setBackground(new java.awt.Color(255, 255, 255));
        casilla_33.setText("33");
        casilla_33.setToolTipText("");
        casilla_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_33.setOpaque(true);
        add(casilla_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        casilla_34.setBackground(new java.awt.Color(102, 102, 102));
        casilla_34.setText("34");
        casilla_34.setToolTipText("");
        casilla_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_34.setOpaque(true);
        add(casilla_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 40));

        casilla_35.setBackground(new java.awt.Color(255, 255, 255));
        casilla_35.setText("35");
        casilla_35.setToolTipText("");
        casilla_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_35.setOpaque(true);
        add(casilla_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 40, 40));

        casilla_36.setBackground(new java.awt.Color(102, 102, 102));
        casilla_36.setText("36");
        casilla_36.setToolTipText("");
        casilla_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_36.setOpaque(true);
        add(casilla_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, 40));

        casilla_47.setBackground(new java.awt.Color(102, 102, 102));
        casilla_47.setText("47");
        casilla_47.setToolTipText("");
        casilla_47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_47.setOpaque(true);
        add(casilla_47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 40));

        casilla_41.setBackground(new java.awt.Color(102, 102, 102));
        casilla_41.setText("41");
        casilla_41.setToolTipText("");
        casilla_41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_41.setOpaque(true);
        add(casilla_41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 40, 40));

        casilla_42.setBackground(new java.awt.Color(255, 255, 255));
        casilla_42.setText("42");
        casilla_42.setToolTipText("");
        casilla_42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_42.setOpaque(true);
        add(casilla_42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 40, 40));

        casilla_43.setBackground(new java.awt.Color(102, 102, 102));
        casilla_43.setText("43");
        casilla_43.setToolTipText("");
        casilla_43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_43.setOpaque(true);
        add(casilla_43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 40));

        casilla_44.setBackground(new java.awt.Color(255, 255, 255));
        casilla_44.setText("44");
        casilla_44.setToolTipText("");
        casilla_44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_44.setOpaque(true);
        add(casilla_44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 40));

        casilla_45.setBackground(new java.awt.Color(102, 102, 102));
        casilla_45.setText("45");
        casilla_45.setToolTipText("");
        casilla_45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_45.setOpaque(true);
        add(casilla_45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 40, 40));

        casilla_46.setBackground(new java.awt.Color(255, 255, 255));
        casilla_46.setText("46");
        casilla_46.setToolTipText("");
        casilla_46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_46.setOpaque(true);
        add(casilla_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, 40));

        casilla_57.setBackground(new java.awt.Color(255, 255, 255));
        casilla_57.setText("57");
        casilla_57.setToolTipText("");
        casilla_57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_57.setOpaque(true);
        add(casilla_57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 40, 40));

        casilla_51.setBackground(new java.awt.Color(255, 255, 255));
        casilla_51.setText("51");
        casilla_51.setToolTipText("");
        casilla_51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_51.setOpaque(true);
        add(casilla_51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 40));

        casilla_52.setBackground(new java.awt.Color(102, 102, 102));
        casilla_52.setText("52");
        casilla_52.setToolTipText("");
        casilla_52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_52.setOpaque(true);
        add(casilla_52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, 40));

        casilla_53.setBackground(new java.awt.Color(255, 255, 255));
        casilla_53.setText("53");
        casilla_53.setToolTipText("");
        casilla_53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_53.setOpaque(true);
        add(casilla_53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 40, 40));

        casilla_54.setBackground(new java.awt.Color(102, 102, 102));
        casilla_54.setText("54");
        casilla_54.setToolTipText("");
        casilla_54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_54.setOpaque(true);
        add(casilla_54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 40, 40));

        casilla_55.setBackground(new java.awt.Color(255, 255, 255));
        casilla_55.setText("55");
        casilla_55.setToolTipText("");
        casilla_55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_55.setOpaque(true);
        add(casilla_55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 40));

        casilla_56.setBackground(new java.awt.Color(102, 102, 102));
        casilla_56.setText("56");
        casilla_56.setToolTipText("");
        casilla_56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_56.setOpaque(true);
        add(casilla_56, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 40, 40));

        casilla_67.setBackground(new java.awt.Color(102, 102, 102));
        casilla_67.setText("67");
        casilla_67.setToolTipText("");
        casilla_67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_67.setOpaque(true);
        add(casilla_67, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 40, 40));

        casilla_61.setBackground(new java.awt.Color(102, 102, 102));
        casilla_61.setText("61");
        casilla_61.setToolTipText("");
        casilla_61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_61.setOpaque(true);
        add(casilla_61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 40, 40));

        casilla_62.setBackground(new java.awt.Color(255, 255, 255));
        casilla_62.setText("62");
        casilla_62.setToolTipText("");
        casilla_62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_62.setOpaque(true);
        add(casilla_62, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 40));

        casilla_63.setBackground(new java.awt.Color(102, 102, 102));
        casilla_63.setText("63");
        casilla_63.setToolTipText("");
        casilla_63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_63.setOpaque(true);
        add(casilla_63, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 40, 40));

        casilla_64.setBackground(new java.awt.Color(255, 255, 255));
        casilla_64.setText("64");
        casilla_64.setToolTipText("");
        casilla_64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_64.setOpaque(true);
        add(casilla_64, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 40, 40));

        casilla_65.setBackground(new java.awt.Color(102, 102, 102));
        casilla_65.setText("65");
        casilla_65.setToolTipText("");
        casilla_65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_65.setOpaque(true);
        add(casilla_65, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 40));

        casilla_66.setBackground(new java.awt.Color(255, 255, 255));
        casilla_66.setText("66");
        casilla_66.setToolTipText("");
        casilla_66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_66.setOpaque(true);
        add(casilla_66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 40, 40));

        casilla_77.setBackground(new java.awt.Color(255, 255, 255));
        casilla_77.setText("77");
        casilla_77.setToolTipText("");
        casilla_77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_77.setOpaque(true);
        add(casilla_77, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 40, 40));

        casilla_71.setBackground(new java.awt.Color(255, 255, 255));
        casilla_71.setText("71");
        casilla_71.setToolTipText("");
        casilla_71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_71.setOpaque(true);
        add(casilla_71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 40));

        casilla_72.setBackground(new java.awt.Color(102, 102, 102));
        casilla_72.setText("72");
        casilla_72.setToolTipText("");
        casilla_72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_72.setOpaque(true);
        add(casilla_72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 40, 40));

        casilla_73.setBackground(new java.awt.Color(255, 255, 255));
        casilla_73.setText("73");
        casilla_73.setToolTipText("");
        casilla_73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_73.setOpaque(true);
        add(casilla_73, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 40));

        casilla_74.setBackground(new java.awt.Color(102, 102, 102));
        casilla_74.setText("74");
        casilla_74.setToolTipText("");
        casilla_74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_74.setOpaque(true);
        add(casilla_74, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, 40));

        casilla_75.setBackground(new java.awt.Color(255, 255, 255));
        casilla_75.setText("75");
        casilla_75.setToolTipText("");
        casilla_75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        casilla_75.setOpaque(true);
        add(casilla_75, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 40));

        casilla_76.setBackground(new java.awt.Color(102, 102, 102));
        casilla_76.setText("76");
        casilla_76.setToolTipText("");
        casilla_76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        casilla_76.setOpaque(true);
        add(casilla_76, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void casilla_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_00MouseClicked
        establecerRuta(0,0);
    }//GEN-LAST:event_casilla_00MouseClicked

    private void casilla_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_10MouseClicked
        establecerRuta(1,0);
    }//GEN-LAST:event_casilla_10MouseClicked

    private void casilla_20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_20MouseClicked
        establecerRuta(2,0);
    }//GEN-LAST:event_casilla_20MouseClicked

    private void casilla_30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_30MouseClicked
        establecerRuta(3,0);
    }//GEN-LAST:event_casilla_30MouseClicked

    private void casilla_40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_40MouseClicked
        establecerRuta(4,0);
    }//GEN-LAST:event_casilla_40MouseClicked

    private void casilla_50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_50MouseClicked
        establecerRuta(5,0);
    }//GEN-LAST:event_casilla_50MouseClicked

    private void casilla_60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_60MouseClicked
        establecerRuta(6,0);
    }//GEN-LAST:event_casilla_60MouseClicked

    private void casilla_70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_70MouseClicked
        establecerRuta(7,0);
    }//GEN-LAST:event_casilla_70MouseClicked

    private void casilla_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla_01MouseClicked
        establecerRuta(0,1);
    }//GEN-LAST:event_casilla_01MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casilla_00;
    private javax.swing.JLabel casilla_01;
    private javax.swing.JLabel casilla_02;
    private javax.swing.JLabel casilla_03;
    private javax.swing.JLabel casilla_04;
    private javax.swing.JLabel casilla_05;
    private javax.swing.JLabel casilla_06;
    private javax.swing.JLabel casilla_07;
    private javax.swing.JLabel casilla_10;
    private javax.swing.JLabel casilla_11;
    private javax.swing.JLabel casilla_12;
    private javax.swing.JLabel casilla_13;
    private javax.swing.JLabel casilla_14;
    private javax.swing.JLabel casilla_15;
    private javax.swing.JLabel casilla_16;
    private javax.swing.JLabel casilla_17;
    private javax.swing.JLabel casilla_20;
    private javax.swing.JLabel casilla_21;
    private javax.swing.JLabel casilla_22;
    private javax.swing.JLabel casilla_23;
    private javax.swing.JLabel casilla_24;
    private javax.swing.JLabel casilla_25;
    private javax.swing.JLabel casilla_26;
    private javax.swing.JLabel casilla_27;
    private javax.swing.JLabel casilla_30;
    private javax.swing.JLabel casilla_31;
    private javax.swing.JLabel casilla_32;
    private javax.swing.JLabel casilla_33;
    private javax.swing.JLabel casilla_34;
    private javax.swing.JLabel casilla_35;
    private javax.swing.JLabel casilla_36;
    private javax.swing.JLabel casilla_37;
    private javax.swing.JLabel casilla_40;
    private javax.swing.JLabel casilla_41;
    private javax.swing.JLabel casilla_42;
    private javax.swing.JLabel casilla_43;
    private javax.swing.JLabel casilla_44;
    private javax.swing.JLabel casilla_45;
    private javax.swing.JLabel casilla_46;
    private javax.swing.JLabel casilla_47;
    private javax.swing.JLabel casilla_50;
    private javax.swing.JLabel casilla_51;
    private javax.swing.JLabel casilla_52;
    private javax.swing.JLabel casilla_53;
    private javax.swing.JLabel casilla_54;
    private javax.swing.JLabel casilla_55;
    private javax.swing.JLabel casilla_56;
    private javax.swing.JLabel casilla_57;
    private javax.swing.JLabel casilla_60;
    private javax.swing.JLabel casilla_61;
    private javax.swing.JLabel casilla_62;
    private javax.swing.JLabel casilla_63;
    private javax.swing.JLabel casilla_64;
    private javax.swing.JLabel casilla_65;
    private javax.swing.JLabel casilla_66;
    private javax.swing.JLabel casilla_67;
    private javax.swing.JLabel casilla_70;
    private javax.swing.JLabel casilla_71;
    private javax.swing.JLabel casilla_72;
    private javax.swing.JLabel casilla_73;
    private javax.swing.JLabel casilla_74;
    private javax.swing.JLabel casilla_75;
    private javax.swing.JLabel casilla_76;
    private javax.swing.JLabel casilla_77;
    // End of variables declaration//GEN-END:variables
}
